package com.softcorridor.themap;

public class JsonConstants {
    public static final String FARMERS = "farmers";
    public static final String DAILY_REPORT = "dailyreport";
    public static final String REPORT = "report";
    public static final String TRANSACTIONS = "transactions";
    public static final String CLOCKTIME = "clocktime";
    public static final String FARMERID = "farmerid";
    public static final String FARMERIDS = "farmerids";
    public static final String CLOCKDATE = "clockdate";
    public static final String COLLECTIONDATE = "collectiondate";
    public static final String ID = "id";
    public static final String F2 = "finger2";
    public static final String F1 = "finger1";
    public static final String TIME_CREATED = "time_created";
    public static final String DATE = "datecreated";
    public static final String CARD = "card";
    public static final String ACTIVITY_TYPE = "type";
    public static final String LATITUDE = "latitude";
    public static final String LONGITUDE = "longitude";
    public static final String COORDINATES = "coordinates";
    public static final String NFCCARDTEMPLATEONE = "nfc";
    public static final String DOB = "dob";
    public static final String BVN = "bvn";
    public static final String FARMSIZE = "farmsize";
    public static final String GENDER = "gender";
    public static final String FINGERMODE = "FINGER";
    public static final String CARDMODE = "CARD";
    public static final String CONTAINED = "contained";
    public static final String BVNS = "bvns";
    public static final String RIGHTTHUMB = "rightthumb";
    public static final String LEFTTHUMB = "leftthumb";
    public static final String CAPTUREDDATE = "captureddate";

    //MESSAGES
    public static final String STATUS = "status";
    public static final String MESSAGE = "message";
    public static final String SUCCESS = "200";

    public static final String WORK_TIMEID = "work_timeid";
    public static final String STAFFID = "farmerid";
    public static final String ACTIVATED = "activated";
    public static final String OLDPASSWORD = "oldpassword";
    public static final String COUNT = "count";
    public static final String TERMINALIMEI = "imei";
    public static final String ACTIVITY_ID = "atcode";
    public static final String LAST_TX_CODE = "txcount";
    public static final String LOCATION = "location";
    public static final String CLIENT_ID = "clientid";
    public static final String LOCATION_ID = "locationid";
    public static final String CAPTURED_BY = "capturedby";
    public static final String ENTRY_DATE = "entrydate";
    public static final String ENTRY_TIME = "clocktime";
    public static final String VERSION_NAME = "versionname";
    public static final String VERSION_CODE = "versioncode";
    public static final String PHONE = "phone";
    public static final String META = "meta";
    public static final String DATA = "data";
    public static final String NAME = "name";
    public static final String FINGER = "finger";
    public static final String CURRENT_TIME = "currentTime";
    public static final String FINGERS = "fingers";
    public static final String TAG = "tag";
    public static final String CURRENTTIME = "currentTime";
    public static final String DEVICE_SERIAL = "deviceserial";
    public static final String DEVICE_MODEL = "devicemodel";
    public static final String EMPLOYEE_ID = "employeeid";
    public static final String CAPTUREDLOCATIONID = "capturedlocationid";
    public static final String LOGGEDIN = "loggedin";

    public static final String SCANNER_WORKING = "scanner_working";
    public static final String APPURL = "appurl";
    public static final String UPDATE = "update";
    public static final String SIZE = "size";
    public static final String UPDATE_OFFLINE = "UPDATE_OFFLINE";


    public static String OPERATORID = "operatorid";
    public static String MODULEID = "moduleid";
    public static String PROJECT = "project";
    public static String MODULE = "module";
    public static String PROJECTCODE = "projectcode";
    public static String PROJECTID = "projectid";
    public static String INPUTID = "inputid";
    public static String MODULECODE = "modulecode";
    public static String ADMIN = "admin";
    public static String FIRSTNAME = "firstname";
    public static String LASTNAME = "lastname";
    public static String SURNAME = "surname";
    public static String MIDDLENAME = "middlename";
    public static String PASSWORD = "password";
    public static String ACCESSMODULES = "accessmodules";
    public static String PASSPORT = "passport";
    public static String COLLECTIONINPUTS = "collectioninputs";
    public static String DATABASEINITIALIZED = "databaseinitialized";
    public static String LGS = "lgs";
    public static String LGCODE = "lgcode";
    public static String LGNAME = "lgname";
    public static String STATECODE = "statecode";
    public static String STATENAME = "statename";
    public static String QUANTITY = "quantity";
    public static String CENTERPOINT = "centerpoint";
}
